<?php

namespace Database\Seeders;

use App\Models\Penduduk;
use Illuminate\Database\Seeder;

class PendudukSeeder extends Seeder
{
    public function run(): void
    {
        $penduduk = [
            [
                'nik' => '6301010101010001',
                'no_kk' => '6301010101010001',
                'nama_lengkap' => 'Muhammad Rizki',
                'tempat_lahir' => 'Pelaihari',
                'tanggal_lahir' => '1995-03-12',
                'jenis_kelamin' => 'laki-laki',
                'agama' => 'Islam',
                'pekerjaan' => 'Wiraswasta',
                'pendidikan' => 'SMA',
                'status_perkawinan' => 'menikah',
                'kewarganegaraan' => 'WNI',
                'alamat' => 'Jl. Contoh No. 01',
                'rt' => '001',
                'rw' => '001',
                'desa' => 'Contoh Desa',
                'kecamatan' => 'Pelaihari',
                'kabupaten' => 'Tanah Laut',
                'provinsi' => 'Kalimantan Selatan',
                'kode_pos' => '70812',
                'no_telp' => '081234567801',
                'email' => 'rizki@example.test',
            ],

            [
                'nik' => '6301010101010002',
                'no_kk' => '6301010101010002',
                'nama_lengkap' => 'Siti Rahma',
                'tempat_lahir' => 'Banjarmasin',
                'tanggal_lahir' => '1998-07-21',
                'jenis_kelamin' => 'perempuan',
                'agama' => 'Islam',
                'pekerjaan' => 'Guru',
                'pendidikan' => 'S1',
                'status_perkawinan' => 'menikah',
                'kewarganegaraan' => 'WNI',
                'alamat' => 'Jl. Contoh No. 02',
                'rt' => '001',
                'rw' => '001',
                'desa' => 'Contoh Desa',
                'kecamatan' => 'Pelaihari',
                'kabupaten' => 'Tanah Laut',
                'provinsi' => 'Kalimantan Selatan',
                'kode_pos' => '70812',
                'no_telp' => '081234567802',
                'email' => 'rahma@example.test',
            ],

            [
                'nik' => '6301010101010003',
                'no_kk' => '6301010101010003',
                'nama_lengkap' => 'Andi Saputra',
                'tempat_lahir' => 'Banjarbaru',
                'tanggal_lahir' => '2000-01-15',
                'jenis_kelamin' => 'laki-laki',
                'agama' => 'Islam',
                'pekerjaan' => 'Karyawan Swasta',
                'pendidikan' => 'SMA',
                'status_perkawinan' => 'belum_menikah',
                'kewarganegaraan' => 'WNI',
                'alamat' => 'Jl. Contoh No. 03',
                'rt' => '002',
                'rw' => '001',
                'desa' => 'Contoh Desa',
                'kecamatan' => 'Pelaihari',
                'kabupaten' => 'Tanah Laut',
                'provinsi' => 'Kalimantan Selatan',
                'kode_pos' => '70812',
                'no_telp' => '081234567803',
                'email' => null,
            ],

            [
                'nik' => '6301010101010004',
                'no_kk' => '6301010101010004',
                'nama_lengkap' => 'Dewi Lestari',
                'tempat_lahir' => 'Pelaihari',
                'tanggal_lahir' => '1997-11-03',
                'jenis_kelamin' => 'perempuan',
                'agama' => 'Islam',
                'pekerjaan' => 'Ibu Rumah Tangga',
                'pendidikan' => 'SMA',
                'status_perkawinan' => 'menikah',
                'kewarganegaraan' => 'WNI',
                'alamat' => 'Jl. Contoh No. 04',
                'rt' => '002',
                'rw' => '001',
                'desa' => 'Contoh Desa',
                'kecamatan' => 'Pelaihari',
                'kabupaten' => 'Tanah Laut',
                'provinsi' => 'Kalimantan Selatan',
                'kode_pos' => '70812',
                'no_telp' => '081234567804',
                'email' => null,
            ],

            [
                'nik' => '6301010101010005',
                'no_kk' => '6301010101010005',
                'nama_lengkap' => 'Budi Santoso',
                'tempat_lahir' => 'Pelaihari',
                'tanggal_lahir' => '1989-05-27',
                'jenis_kelamin' => 'laki-laki',
                'agama' => 'Islam',
                'pekerjaan' => 'Petani',
                'pendidikan' => 'SMP',
                'status_perkawinan' => 'menikah',
                'kewarganegaraan' => 'WNI',
                'alamat' => 'Jl. Contoh No. 05',
                'rt' => '003',
                'rw' => '001',
                'desa' => 'Contoh Desa',
                'kecamatan' => 'Pelaihari',
                'kabupaten' => 'Tanah Laut',
                'provinsi' => 'Kalimantan Selatan',
                'kode_pos' => '70812',
                'no_telp' => '081234567805',
                'email' => null,
            ],

            [
                'nik' => '6301010101010006',
                'no_kk' => '6301010101010006',
                'nama_lengkap' => 'Nurul Hidayah',
                'tempat_lahir' => 'Banjarmasin',
                'tanggal_lahir' => '2001-09-18',
                'jenis_kelamin' => 'perempuan',
                'agama' => 'Islam',
                'pekerjaan' => 'Mahasiswa',
                'pendidikan' => 'S1',
                'status_perkawinan' => 'belum_menikah',
                'kewarganegaraan' => 'WNI',
                'alamat' => 'Jl. Contoh No. 06',
                'rt' => '003',
                'rw' => '001',
                'desa' => 'Contoh Desa',
                'kecamatan' => 'Pelaihari',
                'kabupaten' => 'Tanah Laut',
                'provinsi' => 'Kalimantan Selatan',
                'kode_pos' => '70812',
                'no_telp' => '081234567806',
                'email' => 'nurul@example.test',
            ],

            [
                'nik' => '6301010101010007',
                'no_kk' => '6301010101010007',
                'nama_lengkap' => 'Fajar Maulana',
                'tempat_lahir' => 'Pelaihari',
                'tanggal_lahir' => '1994-12-09',
                'jenis_kelamin' => 'laki-laki',
                'agama' => 'Islam',
                'pekerjaan' => 'Pedagang',
                'pendidikan' => 'SMA',
                'status_perkawinan' => 'menikah',
                'kewarganegaraan' => 'WNI',
                'alamat' => 'Jl. Contoh No. 07',
                'rt' => '004',
                'rw' => '002',
                'desa' => 'Contoh Desa',
                'kecamatan' => 'Pelaihari',
                'kabupaten' => 'Tanah Laut',
                'provinsi' => 'Kalimantan Selatan',
                'kode_pos' => '70812',
                'no_telp' => '081234567807',
                'email' => null,
            ],

            [
                'nik' => '6301010101010008',
                'no_kk' => '6301010101010008',
                'nama_lengkap' => 'Rina Wulandari',
                'tempat_lahir' => 'Pelaihari',
                'tanggal_lahir' => '1996-06-14',
                'jenis_kelamin' => 'perempuan',
                'agama' => 'Islam',
                'pekerjaan' => 'Karyawan Swasta',
                'pendidikan' => 'S1',
                'status_perkawinan' => 'belum_menikah',
                'kewarganegaraan' => 'WNI',
                'alamat' => 'Jl. Contoh No. 08',
                'rt' => '004',
                'rw' => '002',
                'desa' => 'Contoh Desa',
                'kecamatan' => 'Pelaihari',
                'kabupaten' => 'Tanah Laut',
                'provinsi' => 'Kalimantan Selatan',
                'kode_pos' => '70812',
                'no_telp' => '081234567808',
                'email' => 'rina@example.test',
            ],
        ];

        foreach ($penduduk as $data) {
            Penduduk::create($data);
        }
    }
}
